// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-t5X_r7oFfAYoNgqjK9RwJn1vaZv09o',
    appId: '1:111421988598:web:4eb8492d2f192bc3fa96d7',
    messagingSenderId: '111421988598',
    projectId: 'chat-app-d6df2',
    authDomain: 'chat-app-d6df2.firebaseapp.com',
    storageBucket: 'chat-app-d6df2.appspot.com',
    measurementId: 'G-X76FLSJWQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9FK5u__l_kYx_pFV0fRQiwY_8-p5NQjY',
    appId: '1:111421988598:android:d96937bc738c541ffa96d7',
    messagingSenderId: '111421988598',
    projectId: 'chat-app-d6df2',
    storageBucket: 'chat-app-d6df2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc6Ki0OYQcm6kas2mZNvBF8EvpNr5qCx0',
    appId: '1:111421988598:ios:9cf5fbeb21f8350efa96d7',
    messagingSenderId: '111421988598',
    projectId: 'chat-app-d6df2',
    storageBucket: 'chat-app-d6df2.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc6Ki0OYQcm6kas2mZNvBF8EvpNr5qCx0',
    appId: '1:111421988598:ios:9cf5fbeb21f8350efa96d7',
    messagingSenderId: '111421988598',
    projectId: 'chat-app-d6df2',
    storageBucket: 'chat-app-d6df2.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE-t5X_r7oFfAYoNgqjK9RwJn1vaZv09o',
    appId: '1:111421988598:web:6a7665dc183c3760fa96d7',
    messagingSenderId: '111421988598',
    projectId: 'chat-app-d6df2',
    authDomain: 'chat-app-d6df2.firebaseapp.com',
    storageBucket: 'chat-app-d6df2.appspot.com',
    measurementId: 'G-W2W9DEG9J3',
  );
}
